apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "dri-ingestion-{{ ts_nodash | lower }}"
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "subhodeep2022/spark-bigdata:spark-4.0.1-uc-0.3.1-fix-v4-mssql-opt"
  imagePullPolicy: IfNotPresent 
  # THE FIX: Absolute path starting from the mount point, no subpaths used in volumes
  mainApplicationFile: "local:///opt/airflow/dags/dags-v5/repo/scripts/ingest_dri_data.py"
  sparkVersion: "4.0.1"
  
  driver:
    cores: 1
    memory: "1g"
    serviceAccount: spark-operator-spark
    nodeSelector:
      kubernetes.io/hostname: "aig-datawarehouse-145"
    volumeMounts:
      - name: dags-shared
        mountPath: /opt/airflow/dags # Mount the root of the PVC
        # subPath is REMOVED to allow symlink resolution
        
  executor:
    cores: 2
    instances: 1
    memory: "4g"
    nodeSelector:
      kubernetes.io/hostname: "aig-datawarehouse-145"
    volumeMounts:
      - name: dags-shared
        mountPath: /opt/airflow/dags

  volumes:
    - name: dags-shared
      persistentVolumeClaim:
        claimName: airflow-dags-pvc
        readOnly: true